import { VtmCharacterSheet } from "../types/VtmCharacterSheet";

export const createVtmCharacterSheet = (): VtmCharacterSheet => {
    return {
        name: "Aiko Hoshino",
        chronicle: "Shadows of Tokyo",
        sire: "Hajime Nakamura",
        concept: "Ethereal Artist",
        ambition: "Create an eternal masterpiece",
        desire: "Find redemption through beauty",
        predator: "Sandman",
        clan: "Toreador",
        generation: 12,
        attributes: {
            physical: {
                strength: 2,
                dexterity: 3,
                stamina: 2,
            },
            social: {
                charisma: 4,
                manipulation: 2,
                resolve: 5,
            },
            mental: {
                perception: 3,
                intelligence: 3,
                wits: 4,
            },
        },
        health: 7,
        willpower: 6,
        skills: {
            athletics: 2,
            brawl: 1,
            craft: 4,
            drive: 0,
            firearms: 1,
            melee: 2,
            larceny: 3,
            stealth: 2,
            survival: 1,
            animalken: 0,
            etiquette: 4,
            insight: 3,
            intimidation: 1,
            leadership: 2,
            performance: 5,
            persuasion: 3,
            streetwise: 2,
            subterfuge: 4,
            academics: 3,
            awareness: 3,
            finance: 1,
            investigation: 2,
            medicine: 1,
            occult: 3,
            politics: 2,
            science: 0,
            technology: 1,
        },
        disciplines: {
            presence: 3,
            auspex: 2,
            celerity: 1,
        },
        resonance: "Melancholic",
        hunger: 2,
        humanity: 8,
    };
};
